// This file was generated by Prisma, and assumes you have installed the following:
import dotenv from "dotenv";
import dotenvExpand from "dotenv-expand";
import { defineConfig } from "prisma/config";

const env = dotenv.config();
dotenvExpand.expand(env);

export default defineConfig({
  schema: "prisma/schemas",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
